# Generated by Django 3.0.4 on 2020-06-03 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demand_Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fiscal_Year', models.CharField(default='BLANK', max_length=4)),
                ('Requested_Date', models.DateField(default=datetime.datetime.now)),
                ('Demand_Status', models.CharField(choices=[('Open', 'Open'), ('In - Progress', 'In - Progress'), ('On - Hold', 'On - Hold'), ('Cancelled', 'Cancelled'), ('Closed', 'Closed')], default='BLANK', max_length=25)),
                ('Demand_Id', models.CharField(default='BLANK', max_length=25)),
                ('Portfolio', models.CharField(choices=[('Clinical Decision Support', 'Clinical Decision Support'), ('Clinical Survelliance', 'Clinical Survelliance'), ('Contigo Health', 'Contigo Health'), ('Corp IT', 'Corp IT'), ('Cost Management', 'Cost Management'), ('Development Operations', 'Development Operations'), ('GPO', 'GPO'), ('Infrastructure', 'Infrastructure'), ('Innovatix', 'Innovatix'), ('IPA', 'IPA'), ('Population Health', 'Population Health'), ('PAS', 'PAS'), ('Quality & Population Health', 'Quality & Population Health')], default='BLANK', max_length=100)),
                ('Portfolio_Lead', models.CharField(choices=[('Alex Tatiyants', 'Alex Tatiyants'), ('Chris Ickert', 'Chris Ickert'), ('Denise Juliano', 'Denise Juliano'), ('Greg Montano', 'Greg Montano'), ('Pawan Singh', 'Pawan Singh'), ('Saima Khan', 'Saima Khan'), ('Saji Rajasekharan', 'Saji Rajasekharan'), ('Todd Wilkes', 'Todd Wilkes')], default='BLANK', max_length=50)),
                ('Hiring_Manager', models.CharField(default='BLANK', max_length=50)),
                ('Project', models.CharField(default='BLANK', max_length=100)),
                ('Role', models.CharField(default='BLANK', max_length=100)),
                ('Skillset', models.CharField(default='BLANK', max_length=100)),
                ('Location', models.CharField(choices=[('Off', 'Off'), ('On', 'On'), ('On-Off', 'On-Off')], default='BLANK', max_length=10)),
                ('Onshore_Replacement_Flag', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=3)),
                ('Planned_Start_Date', models.DateField(default=datetime.datetime.now)),
                ('Expected_Start_Date', models.DateField(default=datetime.datetime.now)),
                ('Detailed_Status', models.CharField(choices=[('1 - GAVS Sourcing/Screening', '1 - GAVS Sourcing/Screening'), ('2 - Premier Reviewing Profiles', '2 - Premier Reviewing Profiles'), ('3 - Premier Interviewing', '3 - Premier Interviewing'), ('4 - Candidate Selected', '4 - Candidate Selected'), ('5 - Onboarding in Progress', '5 - Onboarding in Progress'), ('7 - Candidate Started', '7 - Candidate Started'), ('8 - On Hold', '8 - On Hold'), ('9 - Cancelled', '9 - Cancelled')], default='BLANK', max_length=50)),
                ('Notes', models.TextField(default='BLANK')),
                ('Actual_Start_Date', models.DateField(default=datetime.datetime.now)),
                ('Candidate', models.CharField(default='BLANK', max_length=100)),
                ('Client_Feedback', models.CharField(default='BLANK', max_length=200)),
                ('GAVS_Screening_Date', models.DateField(blank='true', null='true')),
                ('Client_Screening_Date', models.DateField(blank='true', null='true')),
                ('Client_Interview_Date', models.DateField(blank='true', null='true')),
                ('Selected_Date', models.DateField(blank='true', null='true')),
                ('Onboard_Initated_Date', models.DateField(blank='true', null='true')),
                ('Log_Date', models.DateField(auto_now=True)),
            ],
        ),
    ]
