# Generated by Django 3.0.4 on 2020-06-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demand_Manager', '0002_auto_20200603_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand_master',
            name='Client_Interview_Date',
            field=models.DateField(blank='true', null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='demand_master',
            name='Client_Screening_Date',
            field=models.DateField(blank='true', null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='demand_master',
            name='GAVS_Screening_Date',
            field=models.DateField(blank='true', null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='demand_master',
            name='Onboard_Initated_Date',
            field=models.DateField(blank='true', null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='demand_master',
            name='Selected_Date',
            field=models.DateField(blank='true', null='true'),
            preserve_default='true',
        ),
    ]
